name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify your Node.js version

    - name: Install dependencies
      run: npm ci



    - name: Build
      run: npm run build # Replace with actual build command if needed

    - name: Deploy
      run: |
        # Add your deployment commands here
        # For example, if deploying to a server, you might use SCP or another tool
        echo "Deploy step - Add your deployment commands here"
