name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    # Remove or comment out the test step if not needed
    # - name: Run tests
    #   run: npm test

    - name: Build project
      run: npm run build

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
        DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r ./dist $DEPLOYMENT_USER@$DEPLOYMENT_SERVER:/path/to/deploy
        ssh -i private_key.pem $DEPLOYMENT_USER@$DEPLOYMENT_SERVER 'cd /path/to/deploy && npm install --production && pm2 restart all'

    - name: Notify Deployment
      run: |
        echo "Deployment complete!"
